### ISSUE TITLE
UBL 2.1 Tests not working

### ISSUE THREAD

**Issue by dgrmunch** [phax/ph-ubl#24]
Some classes seem missing in UBL21Reading.java (branch master):

import oasis.names.specification.ubl.schema.xsd.applicationresponse_21.ApplicationResponseType;
import oasis.names.specification.ubl.schema.xsd.attacheddocument_21.AttachedDocumentType;
import oasis.names.specification.ubl.schema.xsd.awardednotification_21.AwardedNotificationType;
import oasis.names.specification.ubl.schema.xsd.billoflading_21.BillOfLadingType;
import oasis.names.specification.ubl.schema.xsd.callfortenders_21.CallForTendersType;
import oasis.names.specification.ubl.schema.xsd.catalogue_21.CatalogueType;
import oasis.names.specification.ubl.schema.xsd.cataloguedeletion_21.CatalogueDeletionType;
import oasis.names.specification.ubl.schema.xsd.catalogueitemspecificationupdate_21.CatalogueItemSpecificationUpdateType;
import oasis.names.specification.ubl.schema.xsd.cataloguepricingupdate_21.CataloguePricingUpdateType;
import oasis.names.specification.ubl.schema.xsd.cataloguerequest_21.CatalogueRequestType;
import oasis.names.specification.ubl.schema.xsd.certificateoforigin_21.CertificateOfOriginType;

....

**Comment by phax** [comment]
The classes are created dynamically, so you need to invoke `mvn process-sources` to create them. Alternatively they are also created, when run `mvn clean install`.
hth

**Comment by dgrmunch** [comment]
Hey @phax, thanks so much!

The `mvn clean install` works!! All the tests seem to work and the classes are correctly created.
So this works!

I have seen a parsin error while running the command though. Not sure if it will affect the overall behavior but I will past it here to let you know ;)

```
</Order>
 cvc-elt.1: Cannot find the declaration of element 'Order'. (org.xml.sax.SAXParseException: cvc-elt.1: Cannot find the declaration of element 'Order'.)
org.xml.sax.SAXParseException; cvc-elt.1: Cannot find the declaration of element 'Order'.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1901)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:741)
        at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.startElement(ValidatorHandlerImpl.java:568)
        at com.sun.xml.bind.v2.runtime.unmarshaller.ValidatingUnmarshaller.startElement(ValidatingUnmarshaller.java:101)
        at com.sun.xml.bind.v2.runtime.unmarshaller.InterningXmlVisitor.startElement(InterningXmlVisitor.java:75)
        at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:168)
        at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:244)
        at com.sun.xml.bind.unmarshaller.DOMScanner.scan(DOMScanner.java:127)
        at com.sun.xml.bind.unmarshaller.DOMScanner.scan(DOMScanner.java:110)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:371)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:348)
        at com.helger.jaxb.IJAXBReader.lambda$read$1(IJAXBReader.java:344)
        at com.helger.jaxb.builder.JAXBReaderBuilder.read(JAXBReaderBuilder.java:172)
        at com.helger.jaxb.IJAXBReader.read(IJAXBReader.java:344)
        at com.helger.ubl22.UBL22FuncTest.testReadAndWriteOrders(UBL22FuncTest.java:274)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)


```

**Comment by phax** [comment]
Hi @dgrmunch thanks - I know, I guess this is caused by the purposely bad tests. So this is okay. And concerning the CIUS: it will be readable with this library 100% - if not, they don't obey to the syntax of UBL or CII and would therefore not qualify as a CIUS.

**Comment by GunterO** [comment]
> The classes are created dynamically, so you need to invoke `mvn process-sources` to create them. Alternatively they are also created, when run `mvn clean install`.
> hth
Maybe you can put this in the wiki or readme. I was looking for this as well for some time :-)

**Comment by phax** [comment]
Okay, will do - thx.
